### ISSUE TITLE
Encoder is seriously flawed in performance due to bytestring immutability

### ISSUE THREAD

**Issue by genbtc** [eweast/BencodePy#3]
The encode program completely chokes on anything > 1MB or so.
ByteStrings are immutable, so every time you do coded_bytes += b'whatever', a new copy is created and the old one is discarded. Even if they were mutable, it would run into cases where it runs out of space to resize the big bytestring and would have to reallocate it.  It can't read your mind and know that you're going to add to it, so when you create the bytestring, nothing stops it from allocating other objects just past the end of the bytestring. 

My proposed solution involves tearing down those, and storing all the bytestrings to a list. (with append) That way you can return b''.join(iterableList)
This iterable method was confirmed and tested, on a 500 entry .dat file ~1.6MB, it went from 245 seconds your way to 5 seconds my way.
This was also how the original coders did it on: https://pypi.python.org/pypi/BitTorrent-bencode

**Comment by eweast** [comment]
I knew better, but I hadn't tried encoding anything large so it slipped by.

It has been fixed.

**Comment by genbtc** [comment]
Looks very good and professional :)
